init
IrinaGavenko/Task-schedule pull request #1
Opened 2018-09-04 16:02 UTC by IrinaGavenko

2018-09-04 22:28 UTC, mulkamanov requested changes

2018-09-04 22:28 UTC, mulkamanov commented on src/task_schedule/core.clj
> +  (run! (fn [task'] (new-task task')) task-list))
Здесь нужно обернуть запуск вектора с тасками в бесконечный цикл. Иначе он только один раз выполнится.
Также попробуй упростить функцию, которая передается в run! первым аргументом.

2018-09-04 22:28 UTC, mulkamanov commented on src/task_schedule/core.clj
> +  (Thread/sleep (task :schedule)))
Сейчас у тебя в :schecule записано не время старта, а задержка. Правильно понимаю, что, просто, для примера в первой итерации?

2018-09-04 22:28 UTC, mulkamanov commented on src/task_schedule/core.clj
> +  [task]
Попробуй использовать деструктуризацию, чтоб упростить дальнейшее использование task-type и params.
https://clojure.org/guides/destructuring

2018-09-05 07:21 UTC, IrinaGavenko commented on src/task_schedule/core.clj
> +  (Thread/sleep (task :schedule)))
Да, все так

2018-09-05 07:37 UTC, IrinaGavenko commented on src/task_schedule/core.clj
> +  [task]
Исправлено

2018-09-05 07:38 UTC, IrinaGavenko commented on src/task_schedule/core.clj
> +  (run! (fn [task'] (new-task task')) task-list))
Цикл добавила (удалила для тестирования и забыла вернуть...)
Функцию тоже поправила, но не уверена, что это именно то, что от ожидалось

2018-09-05 12:07 UTC, merged